version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    container_name: myapp
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"