version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsb-1.0
    network_mode: host
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "10M"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"