version: '3'

services:
  web:
    build: .
    ports:
      - "8088:8088"
    container_name: flask
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"